In [65]:

import pandas as pd
import numpy as np

In [66]:

books = pd.read_csv('BX-Books.csv',encoding='latin-1', sep=';', on_bad_lines='skip')

/var/folders/8f/zsh7smnd15z_gk8v12njmtd00000gn/T/ipykernel_25693/3335364938.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('BX-Books.csv',encoding='latin-1', sep=';', on_bad_lines='skip')

In [67]:
books

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [68]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')

In [69]:
books = books[['ISBN','Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher','Image-URL-L']]
books

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...

In [70]:

books.rename(columns={"Book-Title":'title',
                      'Book-Author':'author',
                     "Year-Of-Publication":'year',
                     "Publisher":"publisher",
                     "Image-URL-L":"image_url"},inplace=True)

/var/folders/8f/zsh7smnd15z_gk8v12njmtd00000gn/T/ipykernel_25693/1441358718.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  books.rename(columns={"Book-Title":'title',

In [71]:
books

,ISBN,title,author,year,publisher,image_url
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...

In [72]:
users = pd.read_csv('BX-Users.csv', encoding='latin-1', sep=';', on_bad_lines='skip')

In [73]:
users

        User-ID                            Location   Age
0             1                  nyc, new york, usa   NaN
1             2           stockton, california, usa 18.00
2             3     moscow, yukon territory, russia   NaN
3             4           porto, v.n.gaia, portugal 17.00
4             5  farnborough, hants, united kingdom   NaN
...         ...                                 ...   ...
278853   278854               portland, oregon, usa   NaN
278854   278855  tacoma, washington, united kingdom 50.00
278855   278856           brampton, ontario, canada   NaN
278856   278857           knoxville, tennessee, usa   NaN
278857   278858                dublin, n/a, ireland   NaN

[278858 rows x 3 columns]

In [74]:
users.isna().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [75]:
books.isna().sum()

ISBN         0
title        0
author       2
year         0
publisher    2
image_url    3
dtype: int64

In [76]:
users.rename(columns={"User-ID":'user_id',
                      'Location':'location',
                     "Age":'age'},inplace=True)

In [77]:
ratings = pd.read_csv('BX-Book-Ratings.csv',encoding='latin-1', sep=';', on_bad_lines='skip')

In [78]:
ratings

         User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149780 rows x 3 columns]

In [79]:
ratings.rename(columns={"User-ID":'user_id',
                      'Book-Rating':'rating'},inplace=True)

In [80]:
ratings

         user_id         ISBN  rating
0         276725   034545104X       0
1         276726   0155061224       5
2         276727   0446520802       0
3         276729   052165615X       3
4         276729   0521795028       6
...          ...          ...     ...
1149775   276704   1563526298       9
1149776   276706   0679447156       0
1149777   276709   0515107662      10
1149778   276721   0590442449      10
1149779   276723  05162443314       8

[1149780 rows x 3 columns]

In [81]:
print(books.shape, users.shape, ratings.shape, sep='\n')

(271360, 6)
(278858, 3)
(1149780, 3)

In [82]:
ratings['user_id'].value_counts()

user_id
11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
          ...
116180        1
116166        1
116154        1
116137        1
276723        1
Name: count, Length: 105283, dtype: int64

In [83]:
pd.set_option('display.float_format', '{:.2f}'.format)
ratings['user_id'].describe()

count   1149780.00
mean     140386.40
std       80562.28
min           2.00
25%       70345.00
50%      141010.00
75%      211028.00
max      278854.00
Name: user_id, dtype: float64

In [84]:
x=ratings['user_id'].value_counts()>120

In [85]:
x

user_id
11676      True
198711     True
153662     True
98391      True
35859      True
          ...
116180    False
116166    False
116154    False
116137    False
276723    False
Name: count, Length: 105283, dtype: bool

In [86]:
x[x].shape

(1539,)

In [87]:
y=x[x].index

In [88]:
y.shape

(1539,)

In [89]:
ratings=ratings[ratings['user_id'].isin(y)]
ratings

         user_id        ISBN  rating
1456      277427  002542730X      10
1457      277427  0026217457       0
1458      277427  003008685X       8
1459      277427  0030615321       0
1460      277427  0060002050       0
...          ...         ...     ...
1149633   276680  1884910033       0
1149634   276680  1888173408       7
1149635   276680  1888173564       8
1149636   276680  1888173572       0
1149637   276680  1931561648       9

[625255 rows x 3 columns]

In [90]:
ratings_with_books = ratings.merge(books, on='ISBN')

In [91]:
ratings_with_books

,user_id,ISBN,rating,title,author,year,publisher,image_url
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...
2,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...
3,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co,http://images.amazon.com/images/P/0030615321.0...
4,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books,http://images.amazon.com/images/P/0060002050.0...
...,...,...,...,...,...,...,...,...
576755,276680,1884910033,0,Fiction Writer's Workshop,Josip Novakovich,1995,F &amp; W Pubns,http://images.amazon.com/images/P/1884910033.0...
576756,276680,1888173408,7,Fairy Tale (Common Reader Editions),Alice Thomas Ellis,2001,Akadine Press,http://images.amazon.com/images/P/1888173408.0...
576757,276680,1888173564,8,Parnassus on Wheels (Common Reader Editions),Christopher Morley,2000,Joiner/Oriel Inc,http://images.amazon.com/images/P/1888173564.0...
576758,276680,1888173572,0,Haunted Bookshop (Common Reader Editions),Christopher Morley,2000,Akadine Press,http://images.amazon.com/images/P/1888173572.0...
576759,276680,1931561648,9,The Time Traveler's Wife (Today Show Book Club...,Audrey Niffenegger,2003,MacAdam/Cage Publishing,http://images.amazon.com/images/P/1931561648.0...

In [92]:
number_rating = ratings_with_books.groupby('title')['rating'].count().reset_index()

In [93]:

number_rating.rename(columns={'rating':'num_of_rating'},inplace=True)

In [94]:
number_rating

                                                    title  num_of_rating
0        A Light in the Storm: The Civil War Diary of ...              3
1                                   Always Have Popsicles              1
2                    Apple Magic (The Collector's series)              1
3        Beyond IBM: Leadership Marketing and Finance ...              1
4        Clifford Visita El Hospital (Clifford El Gran...              1
...                                                   ...            ...
177122                   Ãƒ?Ã‚?berraschung am Valentinstag.              1
177123                                      Ãƒ?Ã‚?lpiraten.              1
177124                     Ãƒ?Ã‚?rger mit Produkt X. Roman.              2
177125                              Ãƒ?Ã‚?stlich der Berge.              1
177126                                  Ãƒ?Ã‚?thique en toc              2

[177127 rows x 2 columns]

In [95]:
final_rating=ratings_with_books.merge(number_rating,on='title')

final_rating

,user_id,ISBN,rating,title,author,year,publisher,image_url,num_of_rating
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,95
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...,7
2,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...,1
3,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co,http://images.amazon.com/images/P/0030615321.0...,1
4,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books,http://images.amazon.com/images/P/0060002050.0...,15
...,...,...,...,...,...,...,...,...,...
576755,276680,1884910033,0,Fiction Writer's Workshop,Josip Novakovich,1995,F &amp; W Pubns,http://images.amazon.com/images/P/1884910033.0...,5
576756,276680,1888173408,7,Fairy Tale (Common Reader Editions),Alice Thomas Ellis,2001,Akadine Press,http://images.amazon.com/images/P/1888173408.0...,1
576757,276680,1888173564,8,Parnassus on Wheels (Common Reader Editions),Christopher Morley,2000,Joiner/Oriel Inc,http://images.amazon.com/images/P/1888173564.0...,2
576758,276680,1888173572,0,Haunted Bookshop (Common Reader Editions),Christopher Morley,2000,Akadine Press,http://images.amazon.com/images/P/1888173572.0...,2
576759,276680,1931561648,9,The Time Traveler's Wife (Today Show Book Club...,Audrey Niffenegger,2003,MacAdam/Cage Publishing,http://images.amazon.com/images/P/1931561648.0...,30

In [96]:
final_rating=final_rating[final_rating['num_of_rating']>=30]

In [97]:
final_rating

,user_id,ISBN,rating,title,author,year,publisher,image_url,num_of_rating
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,95
7,277427,0060177721,0,Finding Moon,Tony Hillerman,1995,Harpercollins,http://images.amazon.com/images/P/0060177721.0...,35
9,277427,0060542128,7,When the Storm Breaks,Heather Lowell,2003,HarperTorch,http://images.amazon.com/images/P/0060542128.0...,34
12,277427,006092988X,0,A Tree Grows in Brooklyn,Betty Smith,1998,Perennial,http://images.amazon.com/images/P/006092988X.0...,46
13,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...,168
...,...,...,...,...,...,...,...,...,...
576748,276680,1573221562,10,Affinity,Sarah Waters,2000,Riverhead Books,http://images.amazon.com/images/P/1573221562.0...,39
576749,276680,1573222038,10,Fingersmith,Sarah Waters,2002,Riverhead Hardcover,http://images.amazon.com/images/P/1573222038.0...,73
576750,276680,1573222267,0,Blue Shoe,Anne Lamott,2002,Riverhead Books,http://images.amazon.com/images/P/1573222267.0...,39
576751,276680,1573229083,7,My Dream of You,Nuala O'Faolain,2002,Riverhead Books,http://images.amazon.com/images/P/1573229083.0...,34
576759,276680,1931561648,9,The Time Traveler's Wife (Today Show Book Club...,Audrey Niffenegger,2003,MacAdam/Cage Publishing,http://images.amazon.com/images/P/1931561648.0...,30

In [98]:
final_rating.drop_duplicates(['user_id','title'],inplace=True)

/var/folders/8f/zsh7smnd15z_gk8v12njmtd00000gn/T/ipykernel_25693/1573401051.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_rating.drop_duplicates(['user_id','title'],inplace=True)

In [99]:
final_rating

,user_id,ISBN,rating,title,author,year,publisher,image_url,num_of_rating
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,95
7,277427,0060177721,0,Finding Moon,Tony Hillerman,1995,Harpercollins,http://images.amazon.com/images/P/0060177721.0...,35
9,277427,0060542128,7,When the Storm Breaks,Heather Lowell,2003,HarperTorch,http://images.amazon.com/images/P/0060542128.0...,34
12,277427,006092988X,0,A Tree Grows in Brooklyn,Betty Smith,1998,Perennial,http://images.amazon.com/images/P/006092988X.0...,46
13,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...,168
...,...,...,...,...,...,...,...,...,...
576748,276680,1573221562,10,Affinity,Sarah Waters,2000,Riverhead Books,http://images.amazon.com/images/P/1573221562.0...,39
576749,276680,1573222038,10,Fingersmith,Sarah Waters,2002,Riverhead Hardcover,http://images.amazon.com/images/P/1573222038.0...,73
576750,276680,1573222267,0,Blue Shoe,Anne Lamott,2002,Riverhead Books,http://images.amazon.com/images/P/1573222267.0...,39
576751,276680,1573229083,7,My Dream of You,Nuala O'Faolain,2002,Riverhead Books,http://images.amazon.com/images/P/1573229083.0...,34
576759,276680,1931561648,9,The Time Traveler's Wife (Today Show Book Club...,Audrey Niffenegger,2003,MacAdam/Cage Publishing,http://images.amazon.com/images/P/1931561648.0...,30

In [100]:
final_rating.isna().sum()

user_id          0
ISBN             0
rating           0
title            0
author           0
year             0
publisher        0
image_url        0
num_of_rating    0
dtype: int64

In [101]:
final_rating.dropna(inplace=True)

/var/folders/8f/zsh7smnd15z_gk8v12njmtd00000gn/T/ipykernel_25693/3875732611.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_rating.dropna(inplace=True)

In [102]:
final_rating

,user_id,ISBN,rating,title,author,year,publisher,image_url,num_of_rating
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,95
7,277427,0060177721,0,Finding Moon,Tony Hillerman,1995,Harpercollins,http://images.amazon.com/images/P/0060177721.0...,35
9,277427,0060542128,7,When the Storm Breaks,Heather Lowell,2003,HarperTorch,http://images.amazon.com/images/P/0060542128.0...,34
12,277427,006092988X,0,A Tree Grows in Brooklyn,Betty Smith,1998,Perennial,http://images.amazon.com/images/P/006092988X.0...,46
13,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...,168
...,...,...,...,...,...,...,...,...,...
576748,276680,1573221562,10,Affinity,Sarah Waters,2000,Riverhead Books,http://images.amazon.com/images/P/1573221562.0...,39
576749,276680,1573222038,10,Fingersmith,Sarah Waters,2002,Riverhead Hardcover,http://images.amazon.com/images/P/1573222038.0...,73
576750,276680,1573222267,0,Blue Shoe,Anne Lamott,2002,Riverhead Books,http://images.amazon.com/images/P/1573222267.0...,39
576751,276680,1573229083,7,My Dream of You,Nuala O'Faolain,2002,Riverhead Books,http://images.amazon.com/images/P/1573229083.0...,34
576759,276680,1931561648,9,The Time Traveler's Wife (Today Show Book Club...,Audrey Niffenegger,2003,MacAdam/Cage Publishing,http://images.amazon.com/images/P/1931561648.0...,30

For collab filtering convert to pivot table

In [103]:
book_pivot=final_rating.pivot_table(columns='user_id',index='title',values='rating')
book_pivot

user_id,183,254,507,882,1424,1733,1903,2033,2110,2276,...,275020,275970,276018,276680,277427,277478,277639,278137,278188,278418
title,,,,,,,,,,,,,,,,,,,,,
10 Lb. Penalty,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16 Lighthouse Road,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN
1984,NaN,9.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010: Odyssey Two,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
You Belong to Me and Other True Cases (Ann Rule's Crime Files: Vol. 2),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zlata's Diary: A Child's Life in Sarajevo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [104]:
book_pivot.fillna(0,inplace=True)

In [105]:
book_pivot

user_id,183,254,507,882,1424,1733,1903,2033,2110,2276,...,275020,275970,276018,276680,277427,277478,277639,278137,278188,278418
title,,,,,,,,,,,,,,,,,,,,,
10 Lb. Penalty,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
16 Lighthouse Road,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1984,0.00,9.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1st to Die: A Novel,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2010: Odyssey Two,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
You Belong to Me and Other True Cases (Ann Rule's Crime Files: Vol. 2),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Zlata's Diary: A Child's Life in Sarajevo,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Zoya,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
"\O\"" Is for Outlaw""",0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

Convert pivot_table to csr matrix  before training the model

In [106]:
from scipy.sparse import csr_matrix

In [107]:
book_sparse=csr_matrix(book_pivot)

In [108]:
book_sparse

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 35216 stored elements and shape (2241, 1521)>

In [109]:

from sklearn.neighbors import NearestNeighbors
model = NearestNeighbors(metric='cosine', algorithm='auto', n_neighbors=180, n_jobs=-1)

In [110]:

model.fit(book_sparse)

NearestNeighbors(metric='cosine', n_jobs=-1, n_neighbors=180)

In [111]:

book_pivot.iloc[2,:]

user_id
183      0.00
254      9.00
507      0.00
882      0.00
1424     0.00
         ...
277478   0.00
277639   0.00
278137   0.00
278188   0.00
278418   0.00
Name: 1984, Length: 1521, dtype: float64

In [112]:
distance,suggestion=model.kneighbors(book_pivot.iloc[2,:].values.reshape(1,-1),n_neighbors=6)

In [113]:
suggestion

array([[   2,  957,  150, 2152, 1409,  936]])

In [114]:
distance

array([[0.        , 0.76620799, 0.77789358, 0.80060619, 0.81151668,
        0.81373333]])

In [115]:
for i in range(len(suggestion)):
    print(book_pivot.index[suggestion[i]])

Index(['1984', 'Lying Awake', 'Animal Farm', 'Waiting',
       'Slaughterhouse Five or the Children's Crusade: A Duty Dance With Death',
       'Lord of the Flies'],
      dtype='object', name='title')

In [116]:
book_names=book_pivot.index

In [117]:
book_names

Index(['10 Lb. Penalty', '16 Lighthouse Road', '1984', '1st to Die: A Novel',
       '2010: Odyssey Two', '204 Rosewood Lane', '2061: Odyssey Three',
       '24 Hours', '2nd Chance', '311 Pelican Court',
       ...
       'Xenocide (Ender Wiggins Saga (Paperback))', 'Year of Wonders',
       'Year of Wonders: A Novel of the Plague', 'You Belong To Me',
       'You Belong to Me',
       'You Belong to Me and Other True Cases (Ann Rule's Crime Files: Vol. 2)',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zlata's Diary: A Child's Life in Sarajevo', 'Zoya',
       '\O\" Is for Outlaw"'],
      dtype='object', name='title', length=2241)

In [118]:

book_names[2]

'1984'

In [119]:

final_rating.head()

,user_id,ISBN,rating,title,author,year,publisher,image_url,num_of_rating
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,95
7,277427,0060177721,0,Finding Moon,Tony Hillerman,1995,Harpercollins,http://images.amazon.com/images/P/0060177721.0...,35
9,277427,0060542128,7,When the Storm Breaks,Heather Lowell,2003,HarperTorch,http://images.amazon.com/images/P/0060542128.0...,34
12,277427,006092988X,0,A Tree Grows in Brooklyn,Betty Smith,1998,Perennial,http://images.amazon.com/images/P/006092988X.0...,46
13,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...,168

In [120]:
ids = np.where(final_rating['title'] == "Animal Farm")[0][0]

In [121]:
final_rating.iloc[ids]['image_url']

'http://images.amazon.com/images/P/0451526341.01.LZZZZZZZ.jpg'

In [122]:
book_name=[]
for book_id in suggestion:
    book_name.append(book_pivot.index[book_id])

In [123]:
book_name

[Index(['1984', 'Lying Awake', 'Animal Farm', 'Waiting',
        'Slaughterhouse Five or the Children's Crusade: A Duty Dance With Death',
        'Lord of the Flies'],
       dtype='object', name='title')]

In [124]:
ids_index = []
for name in book_name[0]: 
    ids = np.where(final_rating['title'] == name)[0][0]
    ids_index.append(ids)

In [125]:

for idx in ids_index:
    url = final_rating.iloc[idx]['image_url']
    print(url)

http://images.amazon.com/images/P/0451524934.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0375706062.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0451526341.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0375406530.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0440180295.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0399501487.01.LZZZZZZZ.jpg

In [126]:
import pickle
pickle.dump(model,open('../artifacts/model.pkl','wb'))
pickle.dump(book_names,open('../artifacts/book_names.pkl','wb'))
pickle.dump(final_rating,open('../artifacts/final_rating.pkl','wb'))
pickle.dump(book_pivot,open('../artifacts/book_pivot.pkl','wb'))

# Test Model

In [127]:
def recommend_book(book_name):
    book_id = np.where(book_pivot.index == book_name)[0][0]
    distance, suggestion = model.kneighbors(book_pivot.iloc[book_id,:].values.reshape(1,-1), n_neighbors=6 )
    
    for i in range(len(suggestion)):
            books = book_pivot.index[suggestion[i]]
            for j in books:
                if j == book_name:
                    print(f"You searched '{book_name}'\n")
                    print("The suggestion books are: \n")
                else:
                    print(j)

In [128]:
book_name = "2nd Chance"
recommend_book(book_name)

You searched '2nd Chance'

The suggestion books are:

Four Blind Mice
Roses Are Red
Violets Are Blue
Mortal Prey
The Jury